spring:
  datasource:
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,httptrace
server:
  error:
    include-message: always
